material_mg: [100, 320, 330, 500, 900, 0]
material_eg: [110, 310, 330, 520, 950, 0]

phase_weight: [0, 1, 1, 2, 4, 0]

mobility_bonus: [0, 4, 3, 2, 1, 0]

pawn_structure:
  passed_base: 10
  passed_rank_scale: 3
  passed_mg_divisor: 2
  isolated_mg: 15
  isolated_eg: 20
  doubled_mg: 10
  doubled_eg: 15

rook_file:
  open_mg: 15
  open_eg: 10
  semi_open_mg: 8
  semi_open_eg: 5

bishop_pair:
  bonus_mg: 30
  bonus_eg: 50

king_safety:
  shield_bonus_mg: 10

pst_pawn_mg:
  - [  0,   0,   0,   0,   0,   0,   0,   0]
  - [  5,  10,  10, -20, -20,  10,  10,   5]
  - [  5,  -5, -10,   0,   0, -10,  -5,   5]
  - [  0,   0,   0,  20,  20,   0,   0,   0]
  - [  5,   5,  10,  25,  25,  10,   5,   5]
  - [ 10,  10,  20,  30,  30,  20,  10,  10]
  - [ 50,  50,  50,  50,  50,  50,  50,  50]
  - [  0,   0,   0,   0,   0,   0,   0,   0]

pst_pawn_eg:
  - [  0,   0,   0,   0,   0,   0,   0,   0]
  - [ 10,  10,  10,  10,  10,  10,  10,  10]
  - [ 10,  10,  10,  10,  10,  10,  10,  10]
  - [ 20,  20,  20,  20,  20,  20,  20,  20]
  - [ 30,  30,  30,  30,  30,  30,  30,  30]
  - [ 50,  50,  50,  50,  50,  50,  50,  50]
  - [ 80,  80,  80,  80,  80,  80,  80,  80]
  - [  0,   0,   0,   0,   0,   0,   0,   0]

pst_knight_mg:
  - [-50, -40, -30, -30, -30, -30, -40, -50]
  - [-40, -20,   0,   5,   5,   0, -20, -40]
  - [-30,   5,  10,  15,  15,  10,   5, -30]
  - [-30,   0,  15,  20,  20,  15,   0, -30]
  - [-30,   5,  15,  20,  20,  15,   5, -30]
  - [-30,   0,  10,  15,  15,  10,   0, -30]
  - [-40, -20,   0,   0,   0,   0, -20, -40]
  - [-50, -40, -30, -30, -30, -30, -40, -50]

pst_bishop_mg:
  - [-20, -10, -10, -10, -10, -10, -10, -20]
  - [-10,   5,   0,   0,   0,   0,   5, -10]
  - [-10,  10,  10,  10,  10,  10,  10, -10]
  - [-10,   0,  10,  10,  10,  10,   0, -10]
  - [-10,   5,   5,  10,  10,   5,   5, -10]
  - [-10,   0,   5,  10,  10,   5,   0, -10]
  - [-10,   0,   0,   0,   0,   0,   0, -10]
  - [-20, -10, -10, -10, -10, -10, -10, -20]

pst_rook_mg:
  - [  0,   0,   0,   5,   5,   0,   0,   0]
  - [ -5,   0,   0,   0,   0,   0,   0,  -5]
  - [ -5,   0,   0,   0,   0,   0,   0,  -5]
  - [ -5,   0,   0,   0,   0,   0,   0,  -5]
  - [ -5,   0,   0,   0,   0,   0,   0,  -5]
  - [ -5,   0,   0,   0,   0,   0,   0,  -5]
  - [  5,  10,  10,  10,  10,  10,  10,   5]
  - [  0,   0,   0,   0,   0,   0,   0,   0]

pst_queen_mg:
  - [-20, -10, -10,  -5,  -5, -10, -10, -20]
  - [-10,   0,   5,   0,   0,   0,   0, -10]
  - [-10,   5,   5,   5,   5,   5,   0, -10]
  - [  0,   0,   5,   5,   5,   5,   0,  -5]
  - [ -5,   0,   5,   5,   5,   5,   0,  -5]
  - [-10,   0,   5,   5,   5,   5,   0, -10]
  - [-10,   0,   0,   0,   0,   0,   0, -10]
  - [-20, -10, -10,  -5,  -5, -10, -10, -20]

pst_king_mg:
  - [ 20,  30,  10,   0,   0,  10,  30,  20]
  - [ 20,  20,   0,   0,   0,   0,  20,  20]
  - [-10, -20, -20, -20, -20, -20, -20, -10]
  - [-20, -30, -30, -40, -40, -30, -30, -20]
  - [-30, -40, -40, -50, -50, -40, -40, -30]
  - [-30, -40, -40, -50, -50, -40, -40, -30]
  - [-30, -40, -40, -50, -50, -40, -40, -30]
  - [-30, -40, -40, -50, -50, -40, -40, -30]

pst_king_eg:
  - [-50, -30, -30, -30, -30, -30, -30, -50]
  - [-30, -30,   0,   0,   0,   0, -30, -30]
  - [-30, -10,  20,  30,  30,  20, -10, -30]
  - [-30, -10,  30,  40,  40,  30, -10, -30]
  - [-30, -10,  30,  40,  40,  30, -10, -30]
  - [-30, -10,  20,  30,  30,  20, -10, -30]
  - [-30, -20, -10,   0,   0, -10, -20, -30]
  - [-50, -40, -30, -20, -20, -30, -40, -50]
